packages:
  - "apps/*"
  - "packages/*"

packageExtensions:
  react-helmet-async:
    peerDependencies:
      react: "^16.8.0 || ^17 || ^18 || ^19"
  "@react-jvectormap/core":
    peerDependencies:
      react: "^16.8.0 || ^17 || ^18 || ^19"
      react-dom: "^16.8.0 || ^17 || ^18 || ^19"
  "@react-jvectormap/world":
    peerDependencies:
      react: "^16.8.0 || ^17 || ^18 || ^19"
      react-dom: "^16.8.0 || ^17 || ^18 || ^19"
